/**
 * The names of the icons the app ships (see src/styles/phosphor.css).
 *
 * Kept out of the component so data modules can reference an icon by name
 * without importing React.
 */
export type IconName =
  | 'anchor'
  | 'arrow-counter-clockwise'
  | 'arrow-left'
  | 'backspace'
  | 'bank'
  | 'bell'
  | 'briefcase'
  | 'calendar-blank'
  | 'caret-right'
  | 'check'
  | 'check-circle'
  | 'clipboard-text'
  | 'clock'
  | 'cooking-pot'
  | 'copy'
  | 'credit-card'
  | 'door-open'
  | 'eye'
  | 'file-arrow-down'
  | 'gear'
  | 'hand-heart'
  | 'hourglass-medium'
  | 'house'
  | 'info'
  | 'list-dashes'
  | 'lock-simple'
  | 'lock-simple-open'
  | 'magnifying-glass'
  | 'martini'
  | 'money'
  | 'notebook'
  | 'paper-plane-tilt'
  | 'pause'
  | 'play'
  | 'plus'
  | 'plus-circle'
  | 'shield-check'
  | 'sneaker-move'
  | 'squares-four'
  | 'translate'
  | 'user'
  | 'user-focus'
  | 'user-plus'
  | 'users-four'
  | 'users-three'
  | 'warning-circle'
  | 'x';
